include: package:pedantic/analysis_options.yaml

analyzer:
#   exclude:
#     - path/to/excluded/files/**

linter:
  rules:
    omit_local_variable_types: false  # I believe types in code help code comprehension 
