name: smart_arg
description: A smart argument parser for Dart
version: 1.0.0
homepage: https://github.com/jcowgar/smart_arg

environment:
  sdk: ">=2.5.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

dependencies:
  path: ^1.6.4
